/* eslint-disable @typescript-eslint/no-explicit-any */
import { NextIntlClientProvider } from "next-intl";
import { getMessages, setRequestLocale } from "next-intl/server";
import { notFound } from "next/navigation";
import { routing } from "@/i18n/routing";
import { Roboto } from "next/font/google";
import { Metadata } from "next";
import ReduxProvider from "@/providers/ReduxProvider";
import Header from "@/components/header";
import Footer from "@/components/footer";
import "./globals.css";

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["400", "500", "700"],
  preload: true,
});

export const metadata: Metadata = {
  title: "Food Ordering App",
  description: "Generated by create next app",
};

export default async function LocaleLayout({
  children,
  params,
}: {
  children: React.ReactNode;
  params: { locale: string };
}) {
  const {locale} = await params

  if (!routing.locales.includes(locale as any)) {
    notFound();
  }

  const messages = await getMessages();
  setRequestLocale(locale);

  const direction = locale === "ar" ? "rtl" : "ltr"; // Change direction for Arabic

  return (
    <html lang={locale} dir={direction}>
      <body className={roboto.className}>
        <NextIntlClientProvider messages={messages}>
          <ReduxProvider>
            <Header />
            {children}
            <Footer />
          </ReduxProvider>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
